#!/bin/bash -l

num_nodes=1
for num_pe in 4
do 
  for comm in "twosided"
  do 
   for part in "regular"
   do 
     for param in 0 #0.1 0.2 0.3
     do
       for run in 0 1 2 3 4 5 6 7 8 9
       do
          ./cpu_batch $num_nodes $num_pe $comm reference 1000 iterative-ginkgo $part $param $run
       done
     done
   done 
  done
done
